name: deploy-test
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout
     - uses: actions/setup-node
       with: node-version: '16'
     - run : npm install 


