name: deploy-test
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout
     - name: Use node 16
       uses: actions/setup-node
       with:
        node-version: '16'
     - run : npm install 


